# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\canvas.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from tests.canvas import Canvas


class Ui_AddIDs(object):
    def setupUi(self, AddIDs):
        AddIDs.setObjectName("AddIDs")
        AddIDs.setMaximumSize(QtCore.QSize(1280, 720))
        self.verticalLayout = QtWidgets.QVBoxLayout(AddIDs)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(AddIDs)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(1280, 720))
        self.frame.setMouseTracking(True)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.overlay = QtWidgets.QLabel(self.frame_2)
        self.overlay.setGeometry(QtCore.QRect(0, 0, 941, 621))
        self.overlay.setMouseTracking(False)
        self.overlay.setObjectName("overlay")

        self.canvas = Canvas()
        self.template_img = QtWidgets.QLabel(self.frame_2)
        self.template_img.setGeometry(QtCore.QRect(0, 0, 947, 623))
        self.template_img.setText("")
        self.template_img.setPixmap(QtGui.QPixmap(".\\img/MGI_Blank Lvl1.png"))
        self.template_img.setScaledContents(True)
        self.template_img.setObjectName("template_img")
        self.template_img.raise_()
        self.overlay.raise_()
        self.verticalLayout_2.addWidget(self.frame_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.frame)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel | QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)
        self.verticalLayout.addWidget(self.canvas)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(AddIDs)
        QtCore.QMetaObject.connectSlotsByName(AddIDs)

    def retranslateUi(self, AddIDs):
        _translate = QtCore.QCoreApplication.translate
        AddIDs.setWindowTitle(_translate("AddIDs", "Dialog"))
        self.overlay.setText(_translate("AddIDs", "TextLabel"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    AddIDs = QtWidgets.QDialog()
    ui = Ui_AddIDs()
    ui.setupUi(AddIDs)
    AddIDs.show()
    sys.exit(app.exec_())
