# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tabGroup.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(768, 411)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.toolBox = QtWidgets.QToolBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setObjectName("toolBox")
        self.toolBoxPage1 = QtWidgets.QWidget()
        self.toolBoxPage1.setGeometry(QtCore.QRect(0, 0, 730, 232))
        self.toolBoxPage1.setObjectName("toolBoxPage1")
        self.textBox1_Data = QtWidgets.QPlainTextEdit(self.toolBoxPage1)
        self.textBox1_Data.setGeometry(QtCore.QRect(0, 30, 800, 80))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textBox1_Data.sizePolicy().hasHeightForWidth())
        self.textBox1_Data.setSizePolicy(sizePolicy)
        self.textBox1_Data.setObjectName("textBox1_Data")
        self.idTtfComboBox_1 = QtWidgets.QFontComboBox(self.toolBoxPage1)
        self.idTtfComboBox_1.setGeometry(QtCore.QRect(0, 0, 226, 22))
        self.idTtfComboBox_1.setObjectName("idTtfComboBox_1")
        self.toolBox.addItem(self.toolBoxPage1, "")
        self.toolBoxPage2 = QtWidgets.QWidget()
        self.toolBoxPage2.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.toolBoxPage2.setObjectName("toolBoxPage2")
        self.textBox2_Data = QtWidgets.QPlainTextEdit(self.toolBoxPage2)
        self.textBox2_Data.setGeometry(QtCore.QRect(0, 30, 800, 80))
        self.textBox2_Data.setObjectName("textBox2_Data")
        self.idTtfComboBox_2 = QtWidgets.QFontComboBox(self.toolBoxPage2)
        self.idTtfComboBox_2.setGeometry(QtCore.QRect(0, 0, 226, 22))
        self.idTtfComboBox_2.setObjectName("idTtfComboBox_2")
        self.toolBox.addItem(self.toolBoxPage2, "")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.page.setObjectName("page")
        self.toolBox.addItem(self.page, "")
        self.verticalLayout_2.addWidget(self.toolBox)
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 768, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textBox1_Data.setPlaceholderText(_translate("MainWindow",
                                                         "\"Sherice Marytal\", \"Mirabell Madrigal\", \"Jazmine Topples\", \"Mary Poppins\", \"Kim Possible\",\n"
                                                         "\"Ron Stoppable\", \"Kermit the Frog\", \"Danny Phantom\", \"Mickey Mouse\""))

        self.toolBox.setItemText(self.toolBox.indexOf(self.toolBoxPage1), _translate("MainWindow", "TextBox1"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.toolBoxPage2), _translate("MainWindow", "TextBox2"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Page"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
